services:
  fastapi:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_container
    image: fastapi_app
    environment:
      - DATABASE_URL=postgresql://postgres:test123@db:5432/mydatabase
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
  
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_UESR: postgres
      POSTGRES_PASSWORD: test123
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db: